# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # All other permissions are set to none
  checks: write
  contents: read
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v2
      - name: Danger
        uses: danger/kotlin@1.0.0-beta4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
